stages:
- build
- test

build_main:
  stage: build
  script:
    - qmake
    - make
  tags:
    - qt
    - c++

build_tests:
  stage: test
  script:
   - qmake
   - make
   - cd tests && qmake && make 
  tags:
    - qt
    - c++
