stages:
- build

build_and_test:
  stage: build
  image: g76r/qt6-builder:20230729
  script:
    - qmake
    - make
    - (cd tests && qmake && make && for D in $(grep SUBDIRS ./tests.pro|cut -d= -f2); do (cd $D; echo ==== $D ====; [ -e ./run_test ] && ./run_test || ./test); done)
  tags:
    - qt
    - c++
