stages:
- build
- test

build_main:
  stage: build
  script:
    - cd ..
    - git clone https://gitlab.com/g76r/libqtpf.git
    - (cd libqtpf && qmake && make)
    - cd -
    - qmake INCLUDEPATH+=libqtpf
    - make
  tags:
    - qt
    - c++

build_tests:
  stage: test
  script:
    - cd ..
    - git clone https://gitlab.com/g76r/libqtpf.git
    - (cd libqtpf && qmake && make)
    - cd -
    - qmake INCLUDEPATH+=libqtpf
    - make
    - cd tests && qmake && make 
  tags:
    - qt
    - c++
