stages:
- build
- test

build_main:
  stage: build
  script:
    - cd ..
    - git clone https://gitlab.com/g76r/libqtpf.git
    - (cd libqtpf && qmake && make)
    - cd -
    - qmake INCLUDEPATH+=libqtpf
    - make
  tags:
    - qt
    - c++

build_tests:
  stage: test
  script:
    - cd ..
    - git clone https://gitlab.com/g76r/libqtpf.git
    - (cd libqtpf && qmake && make)
    - cd -
    - qmake INCLUDEPATH+=libqtpf
    - make
    - cd tests && qmake && make
    - (cd ..; for D in $(grep SUBDIRS ./tests.pro|cut -d= -f2); do (cd $D; echo ==== $D ====; [ -e ./run_test ] && ./run_test || ./test); done)
  tags:
    - qt
    - c++
